- id: taplo
  name: taplo
  description: ""
  entry: taplo fmt
  language: python
  types: [toml]
  args: []
  require_serial: false
  additional_dependencies: ["taplo==0.9.3"]
  minimum_pre_commit_version: "0"
